#!/bin/bash
set -e; 

# Check if name is specified
if [[ $1 == sidekiq:* ]]; then
    if [[ -z $2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP="$2"
        # Check if app exists with the same name
        if [[ -d "$DOKKU_ROOT/$APP" ]]; then
            APP_EXISTS=true
        else
            APP_EXISTS=false
        fi
    fi
fi

case "$1" in

  sidekiq:activate)
    echo "ACTIVE" > "$DOKKU_ROOT/$APP/DEPLOY_SIDEKIQ"
    echo "-----> Sidekiq automatic deployment activated for $2"
    ;;

  sidekiq:deactivate)
    echo "-----> Sidekiq automatic deployment deactivated for $2"
    rm "$DOKKU_ROOT/$APP/DEPLOY_SIDEKIQ"
    if [[ -f "$DOKKU_ROOT/$APP/WORKER" ]]; then
        oldid=$(< "$DOKKU_ROOT/$APP/WORKER")
        if ps -p $oldid > /dev/null
        then
          echo "-----> Killing old worker app $oldid"
          docker kill $oldid > /dev/null
        fi
        rm $DOKKU_ROOT/$APP/WORKER
    fi
   ;;

  help)
    cat && cat<<EOF
    sidekiq:activate   <app>     Activate deployments of sidekiq container
    sidekiq:deactivate <app>     Deactivate deployment of sidekiq container
EOF
    ;;

esac
cat
